/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CapabilitiesResponse {
  capabilities: Capabilities;
  versions: string;
  [k: string]: unknown;
}
/**
 * Describes the features of the specification which a data connector implements.
 */
export interface Capabilities {
  explain?: unknown;
  mutations?: MutationCapabilities | null;
  query?: QueryCapabilities | null;
  relationships?: unknown;
  [k: string]: unknown;
}
export interface MutationCapabilities {
  /**
   * Whether or not nested inserts to related collections are supported
   */
  nested_inserts?: {
    [k: string]: unknown;
  };
  returning?: unknown;
  [k: string]: unknown;
}
export interface QueryCapabilities {
  /**
   * Does the agent support foreach queries, i.e. queries with variables
   */
  foreach?: {
    [k: string]: unknown;
  };
  /**
   * Does the agent support ordering by an aggregated array relationship?
   */
  order_by_aggregate?: {
    [k: string]: unknown;
  };
  /**
   * Does the agent support comparisons that involve related collections (ie. joins)?
   */
  relation_comparisons?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
