/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MutationResponse {
  /**
   * The results of each mutation operation, in the same order as they were received
   */
  operation_results: MutationOperationResults[];
  [k: string]: unknown;
}
export interface MutationOperationResults {
  /**
   * The number of rows affected by the mutation operation
   */
  affected_rows: number;
  /**
   * The rows affected by the mutation operation
   */
  returning?:
    | {
        [k: string]: RowFieldValue;
      }[]
    | null;
  [k: string]: unknown;
}
export interface RowFieldValue {
  [k: string]: unknown;
}
