name: DDN Assets

on:
  push:
    branches:
      - "main"

env:
  DATA_TAG: data.${{ github.sha }}
  DATA_SERVER_TAG: data-server.${{ github.sha }}
  DDN_ASSETS_VERSION: v0.2.0

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push data image
        run: |
          export NDC_HUB_GIT_REPO_FILE_PATH=$PWD
          echo "NDC_HUB_GIT_REPO_FILE_PATH = $NDC_HUB_GIT_REPO_FILE_PATH"
          export CONN_HUB_DATA_SERVER_URL="https://storage.googleapis.com/staging-connector-platform-registry/assets"
          echo "CONN_HUB_DATA_SERVER_URL = $CONN_HUB_DATA_SERVER_URL"

          pushd docker/data
            echo "Downloading ddn-assets"
            wget https://github.com/hasura/ddn-assets/releases/download/$DDN_ASSETS_VERSION/ddn-assets
            chmod +x ddn-assets

            # TODO: get rid of this after fixing https://github.com/hasura/ddn-assets/issues/7
            mkdir assets

            echo "Running ddn-assets"
            ./ddn-assets generate

            docker build -t ghcr.io/hasura/ndc-hub:$DATA_TAG . --push
          popd

      - name: Build and push data server image
        run: |
          pushd docker/server
            docker build --build-arg DATA_TAG=$DATA_TAG -t ghcr.io/hasura/ndc-hub:$DATA_SERVER_TAG . --push
          popd
