name: format

on:
  push:

jobs:
  cargo-fmt:
    name: check formatting with cargo fmt
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUSTFLAGS: "-D warnings" # fail on warnings
    steps:
      - uses: actions/checkout@v4

      - name: install tools
        run: |
          rustup show

      - name: check formatting
        run: |
          cargo fmt --all --check
