name: find unused dependencies

on:
  push:

jobs:
  cargo-machete:
    name: find unused dependencies with cargo machete
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUSTFLAGS: "-D warnings" # fail on warnings
    steps:
      - uses: actions/checkout@v4

      - name: install tools
        run: |
          rustup show
          cargo install cargo-machete

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build" # share the cache across jobs
          save-if: false

      - name: find unused dependencies
        run: |
          cargo machete --with-metadata
