name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Run Validations
        run: |
          export NDC_HUB_GIT_REPO_FILE_PATH=$(pwd)
          cd registry-automation
          go run main.go validate
